Description: add a Makefile
 This adds a Makefile.
Author: Niklas Sombert <niklas@ytvwld.de>

--- /dev/null
+++ asciiquarium-1.1/Makefile
@@ -0,0 +1,7 @@
+all:
+	true
+
+install:
+	mkdir -p $(DESTDIR)/usr
+	mkdir -p $(DESTDIR)/usr/games
+	install asciiquarium $(DESTDIR)/usr/games/
